repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: ['types-requests']
-   repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
